[package]
name = "k-snowflake"
version = "2.0.1"
authors = ["KryptonFox"]
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/KryptonFox/k-snowflake"
homepage = "https://github.com/KryptonFox/k-snowflake"
description = "Simple one-dependency implementation of Twitter`s (X) snowflake in rust"

[dependencies]
once_cell = "1.21.1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "snowflakes"
harness = false